language: generic
sudo: required
services:
  -docker

before_install:
  - docker build -f Dockerfile.dev -t meira/docker-react .

script:
  - docker run -e CI=true meira/docker-react npm run test -- --coverage